version: "3.7"
services:
  db:
    image: postgres:13.2-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=alexnikiforova
      - POSTGRES_PASSWORD=~8qXt~|Y~@?IN